CREATE DATABASE RESERVATIONS;

USE RESERVATIONS;

use reservation;

select * from user;

# for admin

create table admin(admin_id int not null,
 admin_name varchar(50),
 admin_email varchar(50),
 admin_password varchar(50),
 primary key(admin_id),
 unique key(admin_email)
 );
insert into admin values(1,'admin','admin@admin.com','admin123');
 select * from admin;
 
 
 
CREATE TABLE USER 
(
ID INT NOT NULL AUTO_INCREMENT,
FIRST_NAME VARCHAR(50),
LAST_NAME VARCHAR(50),
EMAIL VARCHAR(50),
PASSWORD VARCHAR(256), 
PRIMARY KEY (ID),
UNIQUE KEY (EMAIL)
);

CREATE TABLE FLIGHT
(
  ID INT  NOT NULL AUTO_INCREMENT,
  FLIGHT_NUMBER VARCHAR(50)  NOT NULL, 
  OPERATING_AIRLINES VARCHAR(50)  NOT NULL,
  DEPARTURE_CITY VARCHAR(50)  NOT NULL,
  ARRIVAL_CITY VARCHAR(50)  NOT NULL,
  DATE_OF_DEPARTURE VARCHAR(50)  NOT NULL,
  ESTIMATED_DEPARTURE_TIME VARCHAR(50) NOT NULL,  
  PRIMARY KEY (ID)
);

CREATE TABLE PASSENGER
(
  ID         INT NOT NULL AUTO_INCREMENT,
  FIRST_NAME       VARCHAR(256),
  LAST_NAME    VARCHAR(256),
  MIDDLE_NAME   VARCHAR(256),
  EMAIL VARCHAR(50),
  PHONE VARCHAR(50),
  PRIMARY KEY (ID)
);

CREATE TABLE RESERVATION
(
  ID INT NOT NULL AUTO_INCREMENT,
  CHECKED_IN TINYINT(1),
  NUMBER_OF_BAGS INT,
  PASSENGER_ID INT,
  FLIGHT_ID INT,
  CREATED TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (ID),
  FOREIGN KEY (PASSENGER_ID) REFERENCES PASSENGER(ID) ON DELETE CASCADE,
  FOREIGN KEY (FLIGHT_ID) REFERENCES FLIGHT(ID) ON DELETE CASCADE
);

SELECT * FROM USER;

SELECT * FROM PASSENGER ;

SELECT * FROM FLIGHT;

SELECT * FROM RESERVATION;



DROP TABLE USER;
DROP TABLE RESERVATION;
DROP TABLE PASSENGER;
DROP TABLE FLIGHT;

DROP DATABASE RESERVATION;